[package]
name = "opd8n"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Workspace
clap.workspace = true
tokio.workspace = true
futures.workspace = true
color-eyre.workspace = true
op-test-vectors.workspace = true

# External
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
tracing = { version = "0.1" }
