[package]
name = "opfp"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
# Core
hashbrown.workspace = true
serde.workspace = true
tracing.workspace = true
serde_json.workspace = true
tokio.workspace = true
reqwest.workspace = true
futures.workspace = true
color-eyre.workspace = true
tracing-subscriber.workspace = true

# CLI
clap.workspace = true

# Foundry
foundry-common.workspace = true
anvil.workspace = true
anvil-core.workspace = true
cast.workspace = true
forge-script.workspace = true
revm.workspace = true

# Alloy
op-alloy-rpc-types.workspace = true
alloy-rpc-types.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-provider.workspace = true

# OP Types + Kona
op-test-vectors.workspace = true
kona-primitives.workspace = true
kona-derive.workspace = true
superchain-registry.workspace = true
